#应用基本配置
server:
  port: 8080
spring:
  application:
    name: rent-temp-web
  session:
    store-type: redis 
    redis:
      flushMode:IMMEDIATE   #保存会话操作后立即更新到Redis,需要配置成IMMEDIATE模式
#  redis相关配置
  redis:
    database: 0    # Redis数据库索引，默认是0库
    host: 127.0.0.1  #Redis服务器地址
    port: 6379  #服务端口
    timeout: 5000  #设置连接超时时间
    password: 123456  #连接所需的密码
    pool:
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  freemarker:
    charset: utf-8
    template-loader-path: classpath:templates
    suffix: .html
    
  
  mvc:
    static-path-pattern: /static/**
  datasource:     #数据库连接设置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rent?useSSL=true
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

logging:
  config: classpath:logback-spring.xml  #指定日志系统配置文件
rent-oath:
  token:
    key: rent     #用于加密的盐值
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

rent:
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

